export const APP_ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  EMPLOYEES: "/employees",
  EMPLOYEE_ADD: "/employees/add",
  EMPLOYEE_EDIT: "/employees/edit/:id",
  EMPLOYEE_DETAIL: "/employees/:id",
  INTERNS: "/interns",
  INTERN_ADD: "/interns/add",
  INTERN_EDIT: "/interns/edit/:id",
  INTERN_DETAIL: "/interns/:id",
  TRAINEES: "/trainees",
  TRAINEE_ADD: "/trainees/add",
  TRAINEE_EDIT: "/trainees/edit/:id",
  TRAINEE_DETAIL: "/trainees/:id",
  DEPARTMENTS: "/departments",
  DEPARTMENT_ADD: "/departments/add",
  DEPARTMENT_EDIT: "/departments/edit/:id",
  CERTIFICATES: "/certificates",
  SALARY: "/salary",
  SALARY_ADD: "/salary/add",
  SALARY_EDIT: "/salary/edit/:id",
  SALARY_DETAIL: "/salary/:id",
};

export const ROUTE_TITLES = {
  [APP_ROUTES.LOGIN]: "Admin Login",
  [APP_ROUTES.REGISTER]: "Admin Registration",
  [APP_ROUTES.DASHBOARD]: "Dashboard",
  [APP_ROUTES.EMPLOYEES]: "Employees",
  [APP_ROUTES.INTERNS]: "Interns",
  [APP_ROUTES.TRAINEES]: "Trainees",
  [APP_ROUTES.DEPARTMENTS]: "Departments",
  [APP_ROUTES.CERTIFICATES]: "Certificates",
  [APP_ROUTES.SALARY]: "Salary",
};
